// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSY38KfxsL-7p8_YsSPO8Ya03zcJ-Wbzo',
    appId: '1:754897126863:web:cfcdab15cd8869b5f1feba',
    messagingSenderId: '754897126863',
    projectId: 'crafty-bay-43c64',
    authDomain: 'crafty-bay-43c64.firebaseapp.com',
    storageBucket: 'crafty-bay-43c64.firebasestorage.app',
    measurementId: 'G-175N5V2YHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQRzxZgwAm9B2wVosoK_f6MADRJ_xbziU',
    appId: '1:754897126863:android:e2bf2589ae6ca886f1feba',
    messagingSenderId: '754897126863',
    projectId: 'crafty-bay-43c64',
    storageBucket: 'crafty-bay-43c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYOgq6WtJwgMMBEkCZoOhNNaA-NdwER4',
    appId: '1:754897126863:ios:d65a295c8100f980f1feba',
    messagingSenderId: '754897126863',
    projectId: 'crafty-bay-43c64',
    storageBucket: 'crafty-bay-43c64.firebasestorage.app',
    iosBundleId: 'com.example.craftyBey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYOgq6WtJwgMMBEkCZoOhNNaA-NdwER4',
    appId: '1:754897126863:ios:d65a295c8100f980f1feba',
    messagingSenderId: '754897126863',
    projectId: 'crafty-bay-43c64',
    storageBucket: 'crafty-bay-43c64.firebasestorage.app',
    iosBundleId: 'com.example.craftyBey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSY38KfxsL-7p8_YsSPO8Ya03zcJ-Wbzo',
    appId: '1:754897126863:web:9a64fdcde2e8db7cf1feba',
    messagingSenderId: '754897126863',
    projectId: 'crafty-bay-43c64',
    authDomain: 'crafty-bay-43c64.firebaseapp.com',
    storageBucket: 'crafty-bay-43c64.firebasestorage.app',
    measurementId: 'G-CT64HZ7G74',
  );

}